### ISSUE TITLE
Custom Error getting printed in Production Mode

### ISSUE THREAD

**Issue by david-buderus** [upb-uc4/lagom-core#263]
**Describe the bug**
In Production Mode every Custom Error gets printed.

**Expected behavior**
No output.

**Comment by RHelmert** [comment]
Idea: This is because the logback.xml in the resource folder won't get deployed. Thus the default logback of lagom is applied.
[https://www.lagomframework.com/documentation/1.6.x/java/SettingsLogger.html](url)

Information [http://logback.qos.ch/manual/configuration.html](url)
"If you are using Maven and if you place the logback-test.xml under the src/test/resources folder, Maven will ensure that it won't be included in the artifact produced. Thus, you can use a different configuration file, namely logback-test.xml during testing, and another file, namely, logback.xml, in production."
